### PR TITLE
Add ledger example

### PR DESCRIPTION
**Pull request by tschottdorf**
A general ledger is a complete record of financial transactions over the life
of a bank (or other company).
The example here aims to model a bank in a more realistic setting than our
previous bank example(s) do, and tickles contention issues (causing complete
deadlock in the more contended modes) which will be interesting to investigate.
The example may be run both against Postgres and Cockroach.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/63)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I didn't realize you had such in-depth knowledge of accounting Toby. If this whole "software engineering" thing flops, it looks like you'll be fine.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ledger/main.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOWLqFwGlW5kxPYzQ:-KGrOWLrNDk9Cinl_5aS:1102630616) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L40)):*
Should we be encouraging the use of `BIGINT`, given that it's an alias for `INT`?

---

*[ledger/main.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOd-Lleukh-opIayO:-KGrOd-Lleukh-opIayP:1923911440) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L45)):*
Same question with `VARCHAR` vs. `STRING`

---

*[ledger/main.go, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOwqSRXvvi_PsdNo6:-KGrOwqSRXvvi_PsdNo7:1373596374) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L62)):*
What is this used for?

---

*[ledger/main.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQ-QxNlDK4vh4-ABY:-KGrQ-QxNlDK4vh4-ABZ:332469476) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L125)):*
Should we be using [sql.NullInt64](https://golang.org/pkg/database/sql/#NullInt64) for return types? I'm a little unsure of how `sql.ErrNoRows` should be handled.

---

*[ledger/main.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQQJ1eicbecxn26zw:-KGrQQJ1eicbecxn26zx:-223286745) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L126)):*
Maybe make this query as well formatted as the one below.

---

*[ledger/main.go, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrPlmAPlcKez9kp20l:-KGrPlmBp3d542OGHI2_:68465883) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L128)):*
That's actually decently clean with named returns!

---

*[ledger/main.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQaX-WrWoVGLBcqzK:-KGrQaX-WrWoVGLBcqzL:-243712957) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L167)):*
Do you mind explaining this a bit more? Aren't we doing that with `req.Group`?

---

*[ledger/main.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQhUnAKTh-L9e9isd:-KGrQhUnAKTh-L9e9ise:375216246) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L171)):*
Extra line?

---

*[ledger/main.go, line 244 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrR95y0-95TOq4Nxwr:-KGrR95y0-95TOq4Nxws:-509427548) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L244)):*
I've always wondered if there was a more idiomatic way to block indefinitely during the program loop. I guess not.

---

*[ledger/README.md, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrSNQqSFuZBqFA3-j8:-KGrSNQqSFuZBqFA3-j9:1568496012) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/README.md#L14)):*
Maybe add in a command anyway in case the bank example ever goes away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-:-KGrRWD5LGXH3FymYuFD:1905863695)*

**Comment by mberhault** [comment]
Can you add it to the Makefile and the `build/` scripts?
The build scripts can probably be simplified to do `make all` instead of listing them all one by one. Up to you though.

**Comment by tschottdorf** [comment]
@marc done (I went minimal effort).

---

Review status: 1 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[ledger/main.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOWLqFwGlW5kxPYzQ:-KGv3DdrqqxMRyGmHrBj:-2063910654) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L40)):*
On Postgres, int = integer = 4byte: http://www.postgresql.org/docs/current/static/datatype-numeric.html

---

*[ledger/main.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOd-Lleukh-opIayO:-KGv3UrlEWDtSs1xsdqZ:1020401527) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L45)):*
Postgres does not have STRING.

---

*[ledger/main.go, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOwqSRXvvi_PsdNo6:-KGv3dS9kXENBeYVr1QA:1079114311) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L62)):*
For nothing (any more). Removed.

---

*[ledger/main.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQ-QxNlDK4vh4-ABY:-KGv3xLZ3mCuC9MSxnvF:1353998992) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L125)):*
good question, I'll just set them to zero explicitly in that case.

---

*[ledger/main.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQQJ1eicbecxn26zw:-KGv47KAH15ofZloc0rZ:1275516082) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L126)):*
Actually not a fan of that way of formatting (but no other real option with that big a query).

---

*[ledger/main.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQaX-WrWoVGLBcqzK:-KGv4TPwa33Pu-YLRasR:1325070644) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L167)):*
On Cockroach, I think this was mostly https://github.com/cockroachdb/cockroach/issues/6460. On Postgres, I ran into some other limitations of the type system. But now that Summer is landed I think I can reduce this some.
Done, with one awkward cast which was required by Postgres (operator is not unique: unknown + unknown)

---

*[ledger/main.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQhUnAKTh-L9e9isd:-KGv4nUDxPtQ3KeAaT_i:-499146009) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L171)):*
Done.

---

*[ledger/main.go, line 244 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrR95y0-95TOq4Nxwr:-KGv7gP_YCTroSFrVZvU:1874963516) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L244)):*
`os.Signal` is probably more idiomatic, but in this example this does the trick (though I changed it to `<-chan struct{}(nil)` because OCD).

---

*[ledger/README.md, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrSNQqSFuZBqFA3-j8:-KGv32z6gQwKM862AS1Z:-499146009) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/README.md#L14)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-:-KGv8XpnRItGOmUTgIST:308392539)*

**Comment by petermattis** [comment]
Review status: 1 of 6 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[ledger/main.go, line 244 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrR95y0-95TOq4Nxwr:-KGw0ZrIccRIY69X3N1b:-1548328631) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L244)):*
`select{}` will block the current goroutine forever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/63)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ledger/main.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrOd-Lleukh-opIayO:-KGwpdGNarHTdFnt-yrV:1895595268) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L45)):*
You're right, ignore both of these. I forgot that PG compatibility was desired.

---

*[ledger/main.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrQaX-WrWoVGLBcqzK:-KGwq4pLSV9ZVq879e03:720262409) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L167)):*
Thanks for the explanation. Glad to hear that we are not causing this cast :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-:-KGwq3JD7j2RaISBg2aO:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[ledger/main.go, line 244 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/63#-KGrR95y0-95TOq4Nxwr:-KGwqbDiEmYmRUvoVIhn:-499146009) ([raw file](https://github.com/cockroachdb/examples-go/blob/f7a7695d5c81f584ec7d8be3471eaa81253e6512/ledger/main.go#L244)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/63)*

**Pull request merged**
