### PR TITLE
block_writer: clamp latency to both a min and max value

### LINKED ISSUE #94: block_writer fails with "value X is too large to be recorded"
Example failure from `block_writer.stderr`:

```
2017/01/31 07:18:05 value -946739623 is too large to be recorded
```

Which results in a failure of a `supervisor status` for `block_writer`:
```
[02:23:20][TestContinuousLoad_BlockWriter] 	farmer.go:292: block_writer (bwriter6h-desperateleavitt-cockroach-2.eastus.cloudapp.azure.com) is not in expected state RUNNING:
[02:23:20][TestContinuousLoad_BlockWriter] 		block_writer                     EXITED    Jan 31 07:18 AM
[02:23:20][TestContinuousLoad_BlockWriter] 	test_log_scope.go:85: test log files left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/TestContinousLoad-bwriter278254757
```

Failures:
https://teamcity.cockroachdb.com/viewLog.html?buildId=133874&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest1to310g
https://teamcity.cockroachdb.com/viewLog.html?buildId=133875&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest3to510g
https://teamcity.cockroachdb.com/viewLog.html?buildId=133879&tab=buildResultsDiv&buildTypeId=C_BW_4Nodes_6Hours

cc @petermattis since this may be related to recent `block_writer` changes

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #94

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/96)

### CODE REVIEW

**Comment by tamird** [comment]
Monotonic clocks! This still permits (smaller) garbage values :(

**Comment by petermattis** [comment]
What smaller garbage values are you referring to? The problem here wasn't with clock jumps, but with requests that took longer than `maxLatency`.

**Comment by tamird** [comment]
I didn't see any evidence that there wasn't a clock jump.

**Comment by petermattis** [comment]
> I didn't see any evidence that there wasn't a clock jump.

Yeah, my bad. I encountered this myself after @cuongdo re-opened the issue. And the failure was due to a request that took a long time. Note that `28487893083 / 1e9 == 28.5s`.

**Pull request merged**
