### PR TITLE
./block_writer -prepare uses prepared inserts

### PR DESCRIPTION
**Pull request by jordanlewis**
This should be useful to compare the prepare path to the exec path. It
seems to improve performance on a local one-node test cluster by a small
amount at the moment.

```
benchstat exec.txt prepare.txt
name                 old time/op  new time/op  delta
BlockWriter           212µs ± 0%   196µs ± 0%   ~     (p=1.000 n=1+1)
BlockWriterBatch10    309µs ± 0%   261µs ± 0%   ~     (p=1.000 n=1+1)
BlockWriterBatch100   242µs ± 0%   229µs ± 0%   ~     (p=1.000 n=1+1)
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/105)

### CODE REVIEW

**Comment by petermattis** [comment]
I didn't look at this closely yet, but wanted to point out that `cockroachdb/loadgen/kv` uses prepared statements and other operations and is seeing all of the new development. I've been meaning to get rid of `block_writer`. Perhaps we should add a WARNING comment to the file pointing to `cockroachdb/loadgen/kv`. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/105#-:-KiNEkHYrE13ZVo8fp6w:b-p4bz3p)*

**Comment by jseldess** [comment]
@petermattis, if we do get rid of `block_writer`, please let me know a bit ahead of time, as we reference it from one of our "core feature" tutorials: https://www.cockroachlabs.com/docs/demo-automatic-rebalancing.html

**Comment by petermattis** [comment]
@jseldess Roger. There isn't an imminent plan to get rid of `block_writer`. I'd just prefer to see new developments happen on `loadgen/kv`.

**Comment by jordanlewis** [comment]
Whoops, yeah, should have just used `kv`. I'll close this. I'll probably make a patch to `kv` that optionally doesn't use prepared statements since I think that's still a useful point of comparison.

**Pull request closed without merging**
