### PR TITLE
block_writer: add Go benchmark output

### PR DESCRIPTION
**Pull request by cuongdo**
When block_writer terminates (usually through `-max-blocks` or
`-duration` being specified), we now output performance in the Go
benchmark style. For example:

```
BenchmarkBlockWriter	  104320	    191734.5 ns/op
```

Partly addresses cockroachdb/cockroach#7580

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/72)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[block_writer/main.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KN2iXHA84fEXDaDW18a:-KN2iXHA84fEXDaDW18b:324896308) ([raw file](https://github.com/cockroachdb/examples-go/blob/6b1b94e565f05545140ae21e7f423a6785287781/block_writer/main.go#L251)):*
> ```Go
> 			fmt.Printf("\n")
> 			// Output results that mimic Go's built-in benchmark format.
> 			fmt.Printf("BenchmarkBlockWriter\t%8d\t%12.1f ns/op\n",
> ```

If `--duration` was specified, I wonder if we should include it in the benchmark name. Something like `BenchmarkBlockWriter6h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-:-KN2iqlJjvGMrJWBQQ5c:1417088721)*

**Comment by cuongdo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[block_writer/main.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KN2iXHA84fEXDaDW18a:-KN3gEQ3cJvVX7AO9R_I:-1730454667) ([raw file](https://github.com/cockroachdb/examples-go/blob/6b1b94e565f05545140ae21e7f423a6785287781/block_writer/main.go#L251)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If `--duration` was specified, I wonder if we should include it in the benchmark name. Something like `BenchmarkBlockWriter6h`.
</details>
Good idea. Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72)*

**Comment by cuongdo** [comment]
Modified so that benchmark stats are output for every process termination, except `SIGKILL`.

**Comment by tschottdorf** [comment]
LGTM for the last update mod comments.

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[block_writer/main.go, line 215 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXw3TD2d-A9jQajuJu:-KNXw3TD2d-A9jQajuJv:-394352030) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L215)):*
> ```Go
> 		go func() {
> 			time.Sleep(*duration)
> 			close(done)
> ```

There shouldn't be two places that close the channel. You could just move the `*duration > 0` handling before the `wg.Wait()` goroutine and do

```go
if *duration > 0 {
  wg.Add(1)
  go func() {
    time.Sleep(duration)
    wg.Done()
  }()
}
```

---

*[block_writer/main.go, line 227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXwzRIvINFhpimhi3P:-KNXwzRJ8xk4zmW2sMKP:295064271) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L227)):*
> ```Go
> 			// For example, 6*time.Hour normally stringifies as "6h0m0s". This
> 			// regex converts it into a more readable "6h".
> 			d := regexp.MustCompile(`([a-z])0[0a-z]+`).ReplaceAllString(duration.String(), `$1`)
> ```

why not match `[\d+]+[a-z]+`? That would grab `6h` as well and seems more stable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-:-KNXx9TMHv9nbPWvIRy4:2098767522)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[block_writer/main.go, line 215 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXw3TD2d-A9jQajuJu:-KNXxUPXuq4iSUC_ipGe:1170919770) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L215)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> There shouldn't be two places that close the channel. You could just move the `*duration > 0` handling before the `wg.Wait()` goroutine and do
> 
> ```go
> if *duration > 0 {
>   wg.Add(1)
>   go func() {
>     time.Sleep(duration)
>     wg.Done()
>   }()
> }
> ```
</details>
Ah wait, that doesn't do what you want. Well, just write to `done` instead. You can increase its buffering to three.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72)*

**Comment by cuongdo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[block_writer/main.go, line 215 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXw3TD2d-A9jQajuJu:-KNYctsyLcmQw3-z3Gpg:-499146009) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L215)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Ah wait, that doesn't do what you want. Well, just write to `done` instead. You can increase its buffering to three.
</details>
Done.

---

*[block_writer/main.go, line 227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXwzRIvINFhpimhi3P:-KNYeUPDLnUCLjBTb0zT:-644390290) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L227)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> why not match `[\d+]+[a-z]+`? That would grab `6h` as well and seems more stable.
</details>
That would erroneously convert `6h30m`to `6h`. Yeah, it's probably not a big deal but isn't correct either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[block_writer/main.go, line 227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-KNXwzRIvINFhpimhi3P:-KNYuuuNKdWFJ6Nk-hh_:-52737127) ([raw file](https://github.com/cockroachdb/examples-go/blob/8b8c30a67ed834629925fabe6773ece5909b43fe/block_writer/main.go#L227)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> That would erroneously convert `6h30m`to `6h`. Yeah, it's probably not a big deal but isn't correct either.
</details>
You're right, what you've got is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72#-:-KNYv0cFqJ0nRpYLcwEr:1417088721)*

**Comment by cuongdo** [comment]
Instead of automatically deriving the benchmark name, it's now specified by the new flag `benchmark-name`. The continuous load tests are also being modified to pass this through. This is necessary, because in `ContinuousLoadTest`, `test.timeout` is now dictating how long `block_writer` will run. So, only the continuous load test knows the intended duration of the test.

Expect a corresponding update to cockroachdb/cockroach#7973 soon.

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/72)*

**Pull request merged**
