### PR TITLE
Mostly fix CircleCI problems

### PR DESCRIPTION
**Pull request by petermattis**
Retrieval of dependencies now works correctly, but the builds are still
failing because of an upstream failure with
`github.com/opentracing/basictracer-go`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/71)

### CODE REVIEW

**Comment by petermattis** [comment]
Upstream issue: https://github.com/opentracing/basictracer-go/issues/31

**Comment by tamird** [comment]
Given the 4th commit, is the 3rd commit needed?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/71#-:-KLaoLxtJlmNONd6nFx-:1084865735)*

**Comment by petermattis** [comment]
I'm not sure. Seemed saner to do that. I'll experiment with this some more later.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/71#-:-KLapAhFxamSYRc8raV9:1064785795)*

**Comment by petermattis** [comment]
The `basictracer-go` issue has been fixed and now I'm hitting:

```
../.go_workspace/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1462: undefined: grpc.SupportPackageIsVersion2
```

@tamird Seems like we should be using glock or some other vendoring solution here.

**Comment by tamird** [comment]
Indeed; you're seeing that because cockroachdb/cockroach is not using GRPC at head.

**Comment by tamird** [comment]
Stale, closing.

**Pull request closed without merging**
