### PR TITLE
Build kv_bank in example-go

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
Are there any reason why `kv_bank` isn't built? Although It may need to be simplified like https://github.com/cockroachdb/examples-go/pull/22

**Comment by tamird** [comment]
Probably wasn't a priority since we don't intend to support the kv api externally. LGTM if this passes CI, though.

**Comment by mberhault** [comment]
yeah, it's definitely not intended to run anymore. it should still work in insecure mode, but in secure mode, you would need to grab the `node` certs (really not supposed to). It may be best to remove it entirely

**Comment by nak3** [comment]
Oh, I see. Please feel free to close this PR if it should be removed. I'm fine with either.

**Comment by tamird** [comment]
Looks like the build passed, so I'm gonna merge this. Thanks for your contribution!

**Pull request merged**
