### PR TITLE
Add shorturl example.

### PR DESCRIPTION
**Pull request by mberhault**
This has two endpoints:
* `/`
  * no path/query: shows "create url" form
  * path: [0-9a-z.-_~]+ redirects to url pointed to for shorturl
  * ?mode=view&url=<X>: display properties for short url X
  * ?mode=create: endpoint for the creation form
* `/pub/<x>`
  * public redirect (no `X-FORWARDED-EMAIL` required), only redirects
    short URLs marked `public`

This runs on `https://crdb.io`, behind oauth_proxy accepting cockroachlabs gmail accounts.
The `/pub/` URI is whitelisted, bypassing oauth.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/97)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[shorturl/db.go, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWhS3rmbkfUmSxZ7WF:-KdWhS3rmbkfUmSxZ7WG:by0wxo8) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/db.go#L9)):*
> ```Go
> 	"net/url"
> 
> 	// Import postgres driver.
> ```

This comment should be on the `lib/pq` line (one of the linters complains if there is an `_` import without a comment on the previous line)

---

*[shorturl/db.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWhmLbPIdaTg9t1pLF:-KdWhmLbPIdaTg9t1pLG:b-ebuvgl) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/db.go#L63)):*
> ```Go
> 	}
> 
> 	if _, err := db.Exec(fmt.Sprintf("SET DATABASE=%s", dbName)); err != nil {
> ```

This should be unnecessary with the `dbName` in the path. If it is necessary, it's insufficient since the connection may be silently recreated. 

---

*[shorturl/handlers.go, line 131 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWkQ4ogscqrPbEk0G9:-KdWkQ4ogscqrPbEk0GA:bqenqmz) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/handlers.go#L131)):*
> ```Go
> 		return
> 	}
> 	if len(parsedURL.Host) == 0 || len(parsedURL.Scheme) == 0 {
> ```

We should disallow schemes that are not on a whitelist (probably just http, https)

---

*[shorturl/shorty.go, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWi_nqZPFdX6YZqDtq:-KdWi_nqZPFdX6YZqDtr:b-1trlw4) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/shorty.go#L15)):*
> ```Go
> 	initialCounter = "10000"
> 	// allowed characters (for custom shortys).
> 	validChars      = "0123456789abcdefghijklmnopqrstuvwxyz_.-~"
> ```

`~` is not technically allowed in urls without escaping (although this rule has been widely ignored since the early days of the web). URLs that end with punctuation can confuse link detectors, although I don't know if we want to disallow them. 

---

*[shorturl/shorty.go, line 20 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWirXhoyf8Qhaw7EN-:-KdWirXi5VHJmqZVWAi9:b-qc1ed9) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/shorty.go#L20)):*
> ```Go
> 
> var (
> 	validShortyRE   = regexp.MustCompile(fmt.Sprintf(`^[%s]+$`, validChars))
> ```

`.` and `-` are special in regexes; did you want to escape `validChars` first?

---

*[shorturl/shorty.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWjOV998xZEA89rN_M:-KdWjOV998xZEA89rN_N:brk1gh3) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/shorty.go#L22)):*
> ```Go
> 	validShortyRE   = regexp.MustCompile(fmt.Sprintf(`^[%s]+$`, validChars))
> 	reservedShortys = map[string]struct{}{
> 		"pub": {},
> ```

Should probably also reserve `robots.txt`, `favicon.ico`, `index.html`. Or maybe disallow `.` to avoid these kinds of shenanigans completely. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-:-KdWkxwOjyhzN4aEnsCE:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[shorturl/handlers.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-go/97#-KdWlHYV4mML0AHy4gUq:-KdWlHYV4mML0AHy4gUr:b229fxg) ([raw file](https://github.com/cockroachdb/examples-go/blob/a34f6f0bea939949eaccdf4c3294089ad2a22de4/shorturl/handlers.go#L100)):*
> ```Go
> 
> func handleCreate(rw http.ResponseWriter, req *http.Request) {
> 	if req.Method != http.MethodPost {
> ```

This needs XSRF protection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/97)*

**Comment by a-robinson** [comment]
For what it's worth, something about the cert doesn't appear to be liked by the golang TLS libraries. I tried creating a public short-link to our Kubernetes config, and while it loads fine in the browser, the Kubernetes client isn't a fan:

```
$ kubectl create -f https://crdb.io/pub/k8s-statefulset
Unable to connect to the server: x509: certificate signed by unknown authority
```

It's not an important issue at all, just mentioning it. I don't see the same problem when using, for example, https://tiny.cc/cockroachdb-statefulset

**Comment by bdarnell** [comment]
In what environment are you running this? Go binaries try to load CA roots from the default directories of various distributions (e.g. `/etc/ssl/certs`), and if you're in a stale VM or docker image you may need to refresh the ca-certificates package. 

The cert here is letsencrypt, right?

**Comment by a-robinson** [comment]
It's just directly on my macbook. `kubectl` is just calling `http.Get()` with go1.7.2. It's also reproducible with a tiny go program built with go1.8:

```
~/play 0 $ cat httpget.go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	const url = "https://crdb.io/pub/k8s-statefulset"
	resp, err := http.Get(url)
	if err != nil {
		fmt.Printf("get failed: %v\n", err)
		return
	}
	fmt.Println("get succeeded: %d %s", resp.StatusCode, resp.Status)
}
~/play 0 $ go run httpget.go
get failed: Get https://crdb.io/pub/k8s-statefulset: x509: certificate signed by unknown authority
~/play 0 $ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/go"
GORACE=""
GOROOT="/Users/alex/go1.8"
GOTOOLDIR="/Users/alex/go1.8/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0y/zlxqfzj16sgfrxt7p13jqxhw0000gn/T/go-build861884381=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by bdarnell** [comment]
Interesting. On a mac it [reads from the system cert store](https://github.com/golang/go/blob/release-branch.go1.8/src/crypto/x509/root_cgo_darwin.go), so it really should be seeing the same roots as chrome/safari (but not firefox, which manages its own certs independent of the OS). Speaking of which, firefox doesn't like this cert either. (and neither do various other programs I have installed, which mostly use a derivative of the firefox CA list) Looks like we're missing some intermediate certs we need to include in our chain or something like that.

**Comment by mberhault** [comment]
apparently, we may need to pass the chain as well. We do have one, there's just no way to tell oauth_proxy about it.
I was having cert errors on chrome-for-android as well, this is most likely the same reason.

**Comment by mberhault** [comment]
nevermind, letsencrypt generates the following files: `cert.pem  chain.pem  fullchain.pem  privkey.pem`
just had to tell it to use `fullchain.pem` instead of `cert.pem`.

I've done this on `monitoring.crdb.io` and `crdb.io`.
Before using the full chain:
```
$ curl https://crdb.io/pub/k8s-statefulset
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
etc...
```

After using the full chain:
```
$ curl https://crdb.io/pub/k8s-statefulset
<a href="https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/cockroachdb-statefulset.yaml">Found</a>.
```

**Pull request closed without merging**
