### PR TITLE
cpu profiling for sql_bank

### PR DESCRIPTION
**Pull request by vivekmenezes**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/16)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
Can we rewrite this example as a benchmark? We get this stuff and more for free, if we do.

**Comment by petermattis** [comment]
There is already a bank benchmark: `sql/bank_test.go`.

**Comment by tamird** [comment]
@vivekmenezes is this good to close?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/examples-go/16#-:-KC1ECCZ0WKVQfAaBw86:-1350764982)*

**Comment by vivekmenezes** [comment]
Thanks!

**Pull request closed without merging**
