### PR TITLE
clean shadowing lints

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/77)

### CODE REVIEW

**Comment by tamird** [comment]
These "fixes" are bogus. There's a reason we ignore shadowing of `err` in the main repo. :-1: from me.

**Comment by andreimatei** [comment]
I think it's debatable if `err` should be exempt from shadowing rules. I'm surprised you like it, since you're so big on small scopes (and a shadowing means the shadowed `err` is in a big scope).
But anyway to do it we have to hack the makefile with some ugliness. Maybe it's justified in our big repo, but I don't think it's worth it here. I'd say let's just avoid them here. 
2nd opinion?

**Comment by tamird** [comment]
You're "fixing" these by increasing the scope of `err`, not decreasing it.
This PR is appeasing a bug in `go vet`, nothing more.

**Comment by cuongdo** [comment]
I'm not a fan of these changes either, for the same reasons as Tamir.

**Comment by tamird** [comment]
Closing this as stale, please reopen if you disagree.

**Pull request closed without merging**
