### PR TITLE
Brush up ledger example

### PR DESCRIPTION
**Pull request by tschottdorf**
I'm not sure why `SetMaxOpenConns` is important. Anyone wanna shed light on that?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-go/66)

### CODE REVIEW

**Comment by andreimatei** [comment]
I guess you need at least `concurrency` open conns. Not sure is there's some limit by default.

But the reason might have been historically about the lower bound, although I don't know this code. Before we had `SAVEPOINT cockroach_restart`, you couldn't use `db.Txn` to bind your commands to a single connection so that you can get retries to work, so you could hack it by setting `maxOpenConns` to 1. And maybe someone thought you can get the same effect in a multi-threaded scenario by setting it to the number of threads, although that was probably wrong because of races. Just a theory.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> #### Brush up ledger example
> 
> I'm not sure why `SetMaxOpenConns` is important. Anyone wanna shed light on that?
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-:-KJsWFm_VVEh3P7EoTI_:-1047065168)*

**Comment by tschottdorf** [comment]
@andreimatei wanna take a look?

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[ledger/main.go, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-KL2w4Y-vNPdfikZl-VN:-KL2w4Y-vNPdfikZl-VO:-372537148) ([raw file](https://github.com/cockroachdb/examples-go/blob/f32fcbdef024d163d3db54380dd110d01305bc7d/ledger/main.go#L120)):*
> ```Go
> 		if req.Group%100 == 0 {
> 			// Create some fake contention in ~1% of the requests.
> 			req.Group = int64(atomic.LoadInt32(&num) / 100)
> ```

how does this compile? Where is `num` coming from? Shouldn't it be an argument to the function?
At wasn't the hardcoded `1` better? If `num` is a worker's id,  don't you need to create contention between workers?

---

*[ledger/main.go, line 194 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-KL2qMOMU2-nFY-XyQ0L:-KL2qMOMU2-nFY-XyQ0M:1960125872) ([raw file](https://github.com/cockroachdb/examples-go/blob/f32fcbdef024d163d3db54380dd110d01305bc7d/ledger/main.go#L194)):*
> ```Go
> }
> 
> func worker(db *sql.DB, l func(string, ...interface{}), gen func() postingRequest) {
> ```

what's up with the `l` param? Make the worker a struct and initialize it with a name.

---

*[ledger/main.go, line 265 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-KL2q526MKumlqxLQcIy:-KL2q526MKumlqxLQcIz:-407371635) ([raw file](https://github.com/cockroachdb/examples-go/blob/f32fcbdef024d163d3db54380dd110d01305bc7d/ledger/main.go#L265)):*
> ```Go
> 
> 	// Ignoring the error is the easiest way to be reasonably sure the db+table
> 	// exist without bloating the example.
> ```

we have `CREATE ... IF NOT EXISTS`
The blockwriter examples seems to do the init nicely.

---

*[ledger/main.go, line 271 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-KL2qXTN8CkIO5rkrI4o:-KL2qXTN8CkIO5rkrI4p:1398010657) ([raw file](https://github.com/cockroachdb/examples-go/blob/f32fcbdef024d163d3db54380dd110d01305bc7d/ledger/main.go#L271)):*
> ```Go
> 	}
> 
> 	db.SetMaxOpenConns(*concurrency)
> ```

let's get rid of this FUD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-:-KL2wezfETENSpMRcBdX:1417088721)*

**Comment by tschottdorf** [comment]
Wow, incredible how long I've let this one sit. I only found out because I tried to open another PR that updates the README and it wouldn't let me since this one was still open...

I addressed your comments above and removed the contention-generating code, which I think was ultimately misguided (and I definitely didn't explain well where I was going with it).

Sorry again! I'll let you take another look.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[ledger/main.go, line 271 at r3](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-KecOr43bOFba5lKQrN-:-KecOr43bOFba5lKQrN0:bugzg8s) ([raw file](https://github.com/cockroachdb/examples-go/blob/c2c2aab050fff1970de6637bb11f6f5e7cb4d04c/ledger/main.go#L271)):*
> ```Go
> 	// CockroachDB and Postgres.
> 	_, _ = db.Exec(`CREATE DATABASE ledger`)
> 	if _, err := db.Exec(stmtCreate); err != nil {
> ```

why ignore the previous but not this one? i think postgres supports IF NOT EXISTS on tables (but not databases), so probably just need to change `stmtCreate`.

probably do something more than log, on failure, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/66#-:-KecPBJC-ZVjs8SmxguS:bnfp4nl)*

**Comment by tschottdorf** [comment]
Good call, done. TFTR!

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-go/66)*

**Pull request merged**
